stages:
  - build
  - docker
  - scan

backend_build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - cd backend
    - mvn clean package -DskipTests
  artifacts:
    paths:
      - backend/target/*.jar

frontend_build:
  stage: build
  image: node:18
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/

docker_build:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  script:
    - docker build -t $DOCKER_USER/backend ./backend
    - docker build -t $DOCKER_USER/frontend ./frontend
    - docker build -t $DOCKER_USER/db ./database
    - docker push $DOCKER_USER/backend
    - docker push $DOCKER_USER/frontend
    - docker push $DOCKER_USER/db

scan:
  stage: scan
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
  script:
    - docker run --rm aquasec/trivy:0.58.2 trivy image --severity HIGH,CRITICAL $DOCKER_USER/backend || true
    - docker run --rm aquasec/trivy:0.58.2 trivy image --severity HIGH,CRITICAL $DOCKER_USER/frontend || true
    - docker run --rm aquasec/trivy:0.58.2 trivy image --severity HIGH,CRITICAL $DOCKER_USER/db || true