
services:

  # ===== BASE DE DONNÉES =====
  gestion-db:
    container_name: gestion-db
    image: kammounhamdi/gestion-db:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: piece
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - gestion-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-prootpass"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ===== BACKEND =====
  gestion-backend:
    container_name: gestion-backend
    image: kammounhamdi/gestion-backend:latest
    restart: always
    ports:
      - "8883:8883"
    depends_on:
      gestion-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://gestion-db:3306/piece?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpass
    networks:
      - gestion-network

  # ===== FRONTEND =====
  gestion-frontend:
    container_name: gestion-frontend
    image: kammounhamdi/gestion-frontend:latest
    restart: always
    ports:
      - "4200:80"
    depends_on:
      - gestion-backend
    networks:
      - gestion-network

  # ===== SONARQUBE =====
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    restart: always
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - gestion-network
    depends_on:
      - sonar-db

  # ===== SONARQUBE DATABASE =====
  sonar-db:
    image: postgres:15-alpine
    container_name: sonar-db
    restart: always
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar_db_data:/var/lib/postgresql/data
    networks:
      - gestion-network

  # ===== PROMETHEUS =====
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - gestion-network

  # ===== GRAFANA =====
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - gestion-network

# ===== RÉSEAU =====
networks:
  gestion-network:
    driver: bridge

# ===== VOLUMES =====
volumes:
  db_data:
  sonarqube_data:
  sonarqube_logs:
  sonar_db_data:
  grafana_data:
