sonar.projectKey=gestion-piece-front
sonar.projectName=Gestion Piece Frontend
sonar.host.url=http://localhost:9000
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/pfe/lcov.info
sonar.newCode.referenceBranch=main

