sonar.projectKey=gestion-piece-front
sonar.projectName=Gestion Piece Frontend
sonar.host.url=http://localhost:9000
sonar.token=sqa_8e8e7ac9c468a00dc15673affaa74f4558599bfe
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts
sonar.typescript.lcov.reportPaths=coverage/lcov.info
