# Port du backend
server.port=8883

# Base de données — utiliser "db" (nom du service docker-compose)
spring.datasource.url=jdbc:mysql://db:3306/piece?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rootpass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
